AWSTemplateFormatVersion: 2010-09-09

Description: The role for the SimoneSpaccarotella Amplify app

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - amplify.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: Role for the SimoneSpaccarotella Amplify app
      RoleName: !Sub '${AWS::Region}-SimoneSpaccarotella-AmplifyRole'
      Policies:
        - PolicyName: AllowAll
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
      Tags:
        - Key: project
          Value: SimoneSpaccarotellaAmplify

Outputs:
  RoleARN:
    Description: The role ARN
    Value:
      !GetAtt Role.Arn
    Export:
      Name:
        !Sub '${AWS::StackName}-RoleARN'
