name: Node Validation

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ "main" ]
    paths:
      - src/**/*
  pull_request:
    branches: ["main"]
    paths:
      - src/**/*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm build
